name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        compiler: [g++]
        
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake

    - name: Build GTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt -Wno-dev
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Compile tests
      run: |
        cd tests
        ${{ matrix.compiler }} -std=c++17 -o int_tests int_tests.cpp -lgtest -lgtest_main -pthread
        ${{ matrix.compiler }} -std=c++17 -o type_tests type_tests.cpp -lgtest -lgtest_main -pthread

    - name: Run tests
      run: |
        cd g_tests
        ./inttests
        ./typetests

  coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install coverage tools
      run: |
        sudo apt-get install -y lcov gcovr

    - name: Compile with coverage
      run: |
        cd tests
        g++ --coverage -std=c++17 -o int_tests int_tests.cpp -lgtest -lgtest_main -pthread

    - name: Run tests and generate coverage
      run: |
        cd tests
        ./int_tests
        ./type_tests
        gcovr --root ../ --exclude tests/ --xml-pretty -o coverage.xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: tests/coverage.xml